### ISSUE TITLE
Dropping an image always inserts it at the existing cursor position, not the intended drop target

### ISSUE THREAD

**Issue by lylo** [KonnorRogers/rhino-editor#108]
When drag and dropping an image attachment into Rhino, the image is inserted at the current cursor position in the editor regardless of where you place your drag and drop cursor.  

**What I expect to happen**
When I drag an attachment into Rhino, I should be able to choose the drop target by moving my cursor into the intended position. Rhino gives an indication of where this will be (sometimes this is just a normal blinking cursor, at other times it's a horizontal rule – this seems to be a little inconsistent but likely unrelated to this issue), so when I drop the attachment, it should be inserted into the position I have chosen in the document.

**What actually happens**
If my cursor position before dragging and dropping was at the top of the document, when I drag and drop an attachment to a different place, the attachment is always inserted at the top i.e. where the cursor was placed before drag and drop.

I've made a video of this behaviour while running the editor locally in Safari. I can also reproduce this in Chrome. I've also noted that when you drop an image, it inserts a`<p></p>` tag before and after the attachment. Might be a separate bug.

https://github.com/KonnorRogers/rhino-editor/assets/5447/e5760465-cf43-4da1-a305-90d7c53e446e

**Comment by KonnorRogers** [comment]
Hi there! First of all thank you for the report! 

Secondly, this is definitely not expected behavior for the drop location.

As for the `<p>` tags, that is expected, although I'm curious if it should be removed.

https://github.com/KonnorRogers/rhino-editor/blob/cbd94b0e21ded72d05f4060c02256fe488ec8125/src/exports/extensions/attachment.ts#L586-L590

**Comment by lylo** [comment]
> As for the `<p>` tags, that is expected, although I'm curious if it should be removed.

It felt unusual and unexpected to me because if I add an image, then delete it, I wouldn't expect the markup of my document to change. Instead, we get 4 empty paragraphs.

I think this could also cause issues with migrations to/from Trix. Generally speaking switching between Rhino-made rich text areas and Text-made ones works pretty well (assuming your styling doesn't give `<p>` tags margin or padding). In Trix, adding an attachment doesn't insert `<br>` tags which would be the equivalent of what Rhino is doing here. I think there are benefits in mimicking what Trix does (would help with adoption). You'd just need some default y-margin around the `<figure>` I reckon.

**Comment by KonnorRogers** [comment]
@lylo this is one of those decisions that I made that I'm not sure I made the right call. 

So those`<p>` tags technically only get inserted for new attachments. If you're reading from a Trix generated attachment, you won't see them. Now the other piece of the puzzle is that Trix also ships with like 40px of base margin (this is browser default) on `<figure>` I could technically align on that and just leave it to the browser default, but it creates inconsistent styling of the <figure> if someone has a CSS reset leaking through.

**Comment by KonnorRogers** [comment]
Ahhh! I was wrong! Turns out they actually do apply a margin to `<figure>` oops! Will be updating this and removing the extra `<p>` tags in the next release!

<img width="1512" alt="Screenshot 2023-09-07 at 3 59 40 PM" src="https://github.com/KonnorRogers/rhino-editor/assets/26425882/f834b260-43b9-4090-bf97-0c895e7f27f7">

**Comment by lylo** [comment]
Nice one. Thanks! 🙌
