### ISSUE TITLE
Regression in 0.8.1. Editing a rich text with attachments no longer renders the attachments

### ISSUE THREAD

**Issue by lylo** [KonnorRogers/rhino-editor#118]
This issue has been introduced in 0.8.1. 0.8.0 was fine.

If you add an attachment to a rich text and save it, Rhino renders it correctly. If you subsequently edit the rich text, the attachment preview is no longer present in Rhino (the attachment is still present in the database). If you then update the rich text in this state, it no longer renders. This is the same with local storage or S3. Here's a video demonstrating:

https://github.com/KonnorRogers/rhino-editor/assets/5447/ae5e1c89-a96b-4de7-a29f-71abef55b013

**Comment by lylo** [comment]
I suspect this might be related to https://github.com/KonnorRogers/rhino-editor/pull/112/files

**Comment by KonnorRogers** [comment]
@lylo I suspect you may be right. Investigating...

**Comment by KonnorRogers** [comment]
Fixed in #119
