### ISSUE TITLE
In-editor attachment preview broken in iOS Safari

### ISSUE THREAD

**Issue by lylo** [KonnorRogers/rhino-editor#127]
This is a tricky one. I've tried to run the test app locally to verify there but I'm having issues with 0.8.4 that prevent me booting it via Overmind (this is a separate issue that I will need to try and understand).

```
vite    | Error:   Failed to scan for dependencies from entries:
vite    |   /Users/olly/dev/rhino-editor/tests/rails/app/frontend/entrypoints/application.js
vite    | /Users/olly/dev/rhino-editor/tests/rails/app/frontend/entrypoints/collaboration.js
vite    |
vite    |   ✘ [ERROR] Failed to resolve entry for package "rhino-editor". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
vite    |
vite    |     node_modules/.pnpm/esbuild@0.17.18/node_modules/esbuild/lib/main.js:1360:21:
vite    |       1360 │         let result = await callback({
```

To describe the issue itself, if I add a new image to my editor (S3-backed for ActiveStorage) when running in Safari iOS, the image initially appears to load but when I click off the image to another place in the editor then click the image again, the preview disappears. If I save my content, the image appears fine (the attachment is there). If I edit it again, the image preview is broken again... and so on.

Annoyingly I can't replicate this on a desktop browser and there are no console errors. I know I need to demonstrate reproducable steps using the test setup on this repo, but I thought I'd bring this up now anyway just in case there was something obvious.

https://github.com/KonnorRogers/rhino-editor/assets/5447/abf30b80-2c83-4fdc-81e9-765cd921f4d0

**Comment by lylo** [comment]
I got the local Rails server up and running and then hooked it up to my own S3 bucket. I then tethered my iPhone to my Mac and managed to reproduce the issue 😅  

I don't see anything unusual on the iOS Safari console, although this might be of interest:

<img width="995" alt="Screenshot 2023-09-20 at 23 21 30" src="https://github.com/KonnorRogers/rhino-editor/assets/5447/328d9b46-0be7-4ac0-a46f-1132c30c6701">

Here's a video showing the problem:

https://github.com/KonnorRogers/rhino-editor/assets/5447/0741f87c-2159-4bc5-8024-a0d742e1e70b

**Comment by KonnorRogers** [comment]
@lylo that is uhhh...interesting. I don't even have a hunch where to start, but I'll try to get to this as soon as I can.

**Comment by KonnorRogers** [comment]
@lylo so this is really...bizarre. It seems like mobile safari despite updating to the S3 URL in the `<img>` is hanging onto the rendered URL.

The result is basically when the createObjectURL gets revoked, the image disappears. I'm...so confused. I'll be deferring `revokeObjectURL` into the `attachment-delete` callback.

**Comment by lylo** [comment]
Confirmed fixed on my end. Thanks so much @KonnorRogers! 🙏
