### ISSUE TITLE
Can we customize Rhino to have a BubbleMenu

### ISSUE THREAD

**Issue by szluyufeng** [KonnorRogers/rhino-editor#138]
Rhino Editor is based on tiptap. Can we customize it to a floating BubbleMenu instead of a fixed toolbar? For example, can we use "/" to toggle the BubbleMenu? 

Like this project: [](https://novel.sh/)

Rhino Editor is an exciting project. It looks like a perfect alternative to Trix and integrates well with Rails.

**Comment by KonnorRogers** [comment]
Rhino exposes the TipTap editor so yes you should be able to make your own bubble menu

**Comment by KonnorRogers** [comment]
Closing. There will be docs to show how to add a Bubble Menu soon.
