### ISSUE TITLE
Question: is vite required?

### ISSUE THREAD

**Issue by jasonfb** [KonnorRogers/rhino-editor#139]
hey @KonnorRogers - love this!

Is Vite required? can it be used with JSBundling or Shakapacker or Importmap?

I am looking at implementing some rich text for my gem [Hot Glue](https://github.com/hot-glue-for-rails/hot-glue). I already implemented TinyMCE and was going to look at ActionText next, but now I want to give this a try. 
-Jason

**Comment by KonnorRogers** [comment]
Negative. Vite is not required. It should work with JSBundling / Shakapacker. I haven't tested with importmaps, but it should work there as well.
