### ISSUE TITLE
Highlighting text and adding a link can leave you stuck in the link text

### ISSUE THREAD

**Issue by lylo** [KonnorRogers/rhino-editor#140]
I've created a video showing how to reproduce.

* Essentially, type some text but don't leave a trailing space
* Highlight some text and create a link
* Now you can't leave the link without doing some keyboard judo and copy/pasting a space or something

The video also demonstrates that links in the editor are clickable by default which is really annoying. It would be great to change the default for this to false using:

```javascript
  rhinoEditor.starterKitOptions = {
    rhinoLink: {
      openOnClick: false,
    }
  }
```

https://github.com/KonnorRogers/rhino-editor/assets/5447/796292a0-02b2-455b-82fc-f9d449f4860d

**Comment by KonnorRogers** [comment]
I agree `openOnClick` should be false. As for the link issue, I'll take a look when I get a chance.

**Comment by KonnorRogers** [comment]
adding `openOnClick: false` fixes this, and I think should be the default behavior. Will be added in the next release.
