### ISSUE TITLE
How to add class and attributes to input within rhino editor?

### ISSUE THREAD

**Issue by NBlixt** [KonnorRogers/rhino-editor#141]
Is there a way to apply a class or attribute to the input field (technically it's a div) within the Rhino Editor?  When validation fails for a form, I render the form and apply the Bootstrap class `is-invalid` to inputs `class=<%= "is-invalid" if model.errors[:description].any? %>` (my examples will be using a field called "description").

Since the div that takes user input is nested within the `rhino-editor` tag, I can't directly modify the styles of the Rhino Editor's rich text input by adding the `is-invalid` class.  Instead, I use the selector `rhino-editor.is-invalid .trix-content` to apply the same styling from Bootstrap.

Is there a better way to do this?

Another issue is making the error messages available to screen readers.  As an example from when I was still using the Trix editor with Action Text, I add `aria-errormessage="description-errors"` and `aria-invalid="<%= model.errors[:description].any? %>"` to the form input and place another div, `<div id="description-errors">`, below the input to conditionally render an error message if there is one.  This way a screen reader can read the error message when the user focuses on the form input.

Once I switched to the Rhino editor, this no longer worked since, as above with the class issue, the aria attributes are only added to the `rhino-editor` element and not the div with the input.

I can probably write a Stimulus controller that can watch then add the aria attributes to the correct div, but I was hoping there was an easier way to do this.

The main reason why we wanted to switch from Trix to Rhino was so the toolbar was accessible via keyboard, but losing the ability to have a screen reader correctly associate an error message with the input kind of makes it pointless to switch.

**Comment by KonnorRogers** [comment]
> Since the div that takes user input is nested within the rhino-editor tag, I can't directly modify the styles of the Rhino Editor's rich text input by adding the is-invalid class. Instead, I use the selector rhino-editor.is-invalid .trix-content to apply the same styling from Bootstrap.
> Is there a better way to do this?

this is probably the easiest way tbh.

as for your next question of dealing with putting putting aria-invalid and aria-errormessage, you want to put them on the light DOM `contenteditable` area?

how did this work with Trix? Did it forward those aria attributes onto the contenteditable area?? Or did it forward it to the hidden input?

**Comment by NBlixt** [comment]
I'm going to amend my aria comment about `aria-errormessage`.  I thought that was working, but I actually need to use `aria-describedby="id_of_error"` to get the error message to be read with my form inputs when there is an error.  

> how did this work with Trix? Did it forward those aria attributes onto the contenteditable area?? Or did it forward it to the hidden input?

With the Trix editor, I used the rails helper `rich_text_area` for `form_with` to create the rich-text:
`<%= form.rich_text_area :description, class: "form-control #{model.errors[:description].any? ? "is-invalid" : ""}", "aria-invalid": model.errors[:description].any?, "aria-describedby": "description-errors" %>`.

With an error, that produces this HTML:
`<trix-toolbar ...></trix-toolbar>`
`<trix-editor class="form-control" aria-invalid="true" aria-describedby="description-errors" id="model_description" input="model_description_trix_input_model" data-direct-upload-url="http://localhost:3000/rails/active_storage/direct_uploads" data-blob-url-template="http://localhost:3000/rails/active_storage/blobs/redirect/:signed_id/:filename" contenteditable="" role="textbox" aria-label="Description *" trix-id="1" toolbar="trix-toolbar-1">::before</trix-editor>`
And I have a sibling div for the error message.
`<div id="description-errors" class="text-danger" aria-live="polite">[error description]</div>`

So it looks like it is actually attached to the trix editor.

When I turn on a screen reader and click or navigate to the form element for this description, it reads this: "[form label]. Invalid data. Edit text. [error message here]"



For the Rhino editor, it creates HTML like this:
`<rhino-editor..>...`
`<div slot="editor" style="position: relative;">`
`<div class="tiptap ProseMirror trix-content contendeditable="true"...>[content here]</div>`
</div>`
`</rhino-editor>`

If I turn on my screen reader and click or navigate to the failed form input for description, it reads this:
"New line.  Insertion at beginning of text. Edit text."

I then opened up the Inspector in dev tools in my browser and change the inner div with `trix-content` like this:
`<div class="tiptap ProseMirror trix-content contendeditable="true" aria-invalid="true" aria-describedby="description-errors">[content here]</div`.

Now when I click on or navigate to that field, it reads this:
"New line.  Insertion at beginning of text.  Invalid data. Edit text.  Description [error message here]"

With all of that said, if it were possible to add classes and attributes to that inner div, `<div class="tiptap ProseMirror trix-content `, that would fix this issue.

As it stands now, the aria attributes and the form label cannot be associated with the input, at least in my testing.

**Comment by KonnorRogers** [comment]
Perfect. Okay. This helps a ton. I was having a hard time picturing the DOM, but this seems doable. I'll work on a fix for this. I have a few ideas for things, but have to test them first.

**Comment by KonnorRogers** [comment]
Alright, coming in the next release, you should be able to do this:

```erb
<rhino-editor>
  <div 
    slot="editor" 
    aria-invalid="<%= model.errors[:description].any? %>" 
    aria-describedby="description-errors">
  </div>
</rhino-editor>
```

I'm removing an extra wrapping div that isn't needed. There are ways to do it today, but they require writing additional JavaScript, and digging into the JS editor setup.

https://tiptap.dev/api/editor#editor-props

It's not nearly as "HTML-first" as I'd like.

**Comment by NBlixt** [comment]
That's terrific!  Will the `class="tiptap ProseMirror trix-content"` also be added to that div for the editor slot?

**Comment by NBlixt** [comment]
@KonnorRogers, the changes work great.  Thanks so much!
