### ISSUE TITLE
Shrine support?

### ISSUE THREAD

**Issue by tcannonfodder** [KonnorRogers/rhino-editor#147]
Quick question as I'm perusing the docs: does Rhino have a way to extend it so that it can use Shrine instead of ActionStorage? If so, I'm happy to write docs for it!

**Comment by KonnorRogers** [comment]
Probably? It's maybe doable, I just haven't tried it. I just don't know how Shrine will play with ActionText attachments. I'd be happy to add it as a plugin and keep it in the core library, just don't know what it entails currently.

obviously you need to override the DirectUpload adapter, and then modify the backend, but that's the high level overview. No idea what the nitty gritty looks like.

**Comment by KonnorRogers** [comment]
I found this which may be a start:

https://gist.github.com/dpaluy/5d2115ec3a01cd10fec748d4d803dc81

**Comment by tcannonfodder** [comment]
I will dig in and report back!

**Comment by KonnorRogers** [comment]
@tcannonfodder thanks! Let me know what you find, starting place would probably be digging into the AttachmentUpload https://github.com/KonnorRogers/rhino-editor/blob/main/src/exports/attachment-upload.ts and `handleAttachment` are probably the best 2 places to start. I have never used Shrine before so I don't know what it expects

**Comment by tcannonfodder** [comment]
Until I'm able to put together formal documentation around this; here's a very rudimentary implementation of changing Rhino's attachment event handler to use Shrine's Upload Endpoint plugin (https://shrinerb.com/docs/plugins/upload_endpoint):

```javascript
this.addEventListener(`rhino-attachment-add`, async function(event) {
  event.preventDefault()
  const { attachment, target } = event;

  const url = event.target.dataset.directUploadUrl

  let formData = new FormData()
  formData.append('file', attachment.file, attachment.file.name)

  let response = await window.mrujs.fetch(url, {
    method: 'POST',
    body: formData,
    headers: {"Accept": "application/json"}
  });

  let result = await response.json();

  attachment.setAttributes({
    url: result.url,
  });

  attachment.setUploadProgress(100)
})
```

**Comment by tcannonfodder** [comment]
One bug in that prototype is that it doesn't setup the attachment editor for non-image files. Need to find the right calls for that

**Comment by KonnorRogers** [comment]
> Until I'm able to put together formal documentation around this; here's a very rudimentary implementation of changing Rhino's attachment event handler to use Shrine's Upload Endpoint plugin (https://shrinerb.com/docs/plugins/upload_endpoint):
> 
> ```js
> this.addEventListener(`rhino-attachment-add`, async function(event) {
>   event.preventDefault()
>   const { attachment, target } = event;
> 
>   const url = event.target.dataset.directUploadUrl
> 
>   let formData = new FormData()
>   formData.append('file', attachment.file, attachment.file.name)
> 
>   let response = await window.mrujs.fetch(url, {
>     method: 'POST',
>     body: formData,
>     headers: {"Accept": "application/json"}
>   });
> 
>   let result = await response.json();
> 
>   attachment.setAttributes({
>     url: result.url,
>   });
> 
>   attachment.setUploadProgress(100)
> })
> ```

ahhh, the joys of fetch not supporting upload progress 🫠

I gotta go back and visit the docs around error handling, and if it needs to emit any events, but this seems like a solid first pass 👏

**Comment by KonnorRogers** [comment]
#154
