### ISSUE TITLE
Unable to delete image without caption

### ISSUE THREAD

**Issue by lylo** [KonnorRogers/rhino-editor#168]
I'm running the latest Rhino release and I've noticed that it's no longer possible to delete images from my editor unless the caption is populated. 

I think this might be a regression, here's a video of it happening in my app:

https://github.com/KonnorRogers/rhino-editor/assets/5447/96d765bf-01a2-4ec3-b6a8-7c8fc89fa68a

I wouldn't have thought this was due to my configuration, but maybe it is somehow? 

Unfortunately I can't reproduce this using the Rhino test Rails app since I can not longer get that running on macOS Sonomo 14.4.1 (`[ERROR] Failed to resolve entry for package "rhino-editor". The package may have incorrect main/module/exports specified in its package.json`, plus I couldn't run `pnpm run setup` because it requires ruby 3.0.4 which I can't build... anyway,  not that relevant). I will try and get this working when I have time but for now, I have to move on.

**Comment by KonnorRogers** [comment]
🤔 I setup Rhino Editor and ran through everything and was unable to reproduce this in any browser. Do you have a reproduction I could look at by chance?

**Comment by lylo** [comment]
That's helpful thanks, must be something local. Let me dig into it a bit more next week and I'll report back.

**Comment by KonnorRogers** [comment]
🫡 you know where to find me if you need anything!

**Comment by lylo** [comment]
I just spun up a test app which demonstrates the issue:

https://github.com/lylo/rhino-test

This is a standard Rails 7 app using esbuild. The only thing I can think of is that it's a packaging/build issue and some JS isn't being imported correctly, but I can't see where the problem lies. Maybe it's obvious with another pair of eyes!

Here's a video.

https://github.com/KonnorRogers/rhino-editor/assets/5447/664deb77-4df7-4048-90b3-9b8fbe3baaa0

**Comment by KonnorRogers** [comment]
@lylo I'm so confused by this. I checked across all 3 browsers (Chrome / Firefox / Safari), I checked using drag and drop / manually attaching and I still can't reproduce 😭 


https://github.com/KonnorRogers/rhino-editor/assets/26425882/742b085e-b95b-42e1-a7f1-4534e6e23456

**Comment by lylo** [comment]
Thanks for checking @KonnorRogers, this is quite baffling. That looks like my Rails test app, is that correct? (I noticed it's running on port 5000 though, did you change something locally?)

I've tried it on all browsers, with all extensions turned off, private windows and not, and also on my iPhone and I get the same result. I even deployed it to a server so it's not running on my local machine and I see the same issue. The problem seems to be that the focus is always on the caption, it's like all click events are going to the caption unless it's populated. You can't even delete it by using backspace - the cursor hits the caption focus and then all bets are off.

**Comment by lylo** [comment]
@KonnorRogers I've put it up here https://rhino-test-15c820d37315.herokuapp.com and it consistently shows the problem. I've tried this on my Mac as well as on a Windows PC in all browsers and it exhibits the same problem as it does in dev mode. Are you sure you can't reproduce it, even using this deployed app?

**Comment by KonnorRogers** [comment]
@lylo yes I tested it with your app running the Procfile.dev , let me take a look at your heroku deployment and see what's up

**Comment by KonnorRogers** [comment]
@lylo I must've had a cache version with linking or something. I can reproduce now.

**Comment by KonnorRogers** [comment]
@lylo 0.9.3 should be out! Let me know if it works for ya!
