### ISSUE TITLE
[Bug]: Links do not work inside of `<figcaption>`

### ISSUE THREAD

**Issue by KonnorRogers** [KonnorRogers/rhino-editor#209]
https://github.com/KonnorRogers/rhino-editor/discussions/208

**Comment by KonnorRogers** [comment]
Turns out links do work. This is what happens when you blindly copy paste CSS.

 https://github.com/basecamp/trix/blob/e597bc4d943627faa74392d0f85224dc791eb101/assets/trix/stylesheets/content.scss#L66
 
These lines right here remove the color from the link making it seem like it didn't work. This will be removed in the next release and links will have default browser styling @bjhess

**Comment by bjhess** [comment]
Thanks, @KonnorRogers!

I'm not totally clear. If I pull down main of rhino-editor, should links be working and clickable, but just not styled? I'm seeing an `<a>` tag in the markup, but it is not clickable for whatever reason.

**Comment by bjhess** [comment]
1. Of course it isn't clickable in the editor. 🤦 It's getting very Friday in my brain.
2. I might be seeing some oddities on our app with rhino-editor 0.12, but I'm going to wait until Monday to look more because just now it worked fine lol.

Thank you!

**Comment by KonnorRogers** [comment]
Fixed in 0.13.1!
