### ISSUE TITLE
File uploading indicator fills before uploading is complete

### ISSUE THREAD

**Issue by bjhess** [KonnorRogers/rhino-editor#226]
I wanted to share this in case it triggers something for you, @KonnorRogers. See this video simulating uploading an image over slow internet. (Sorry for the long video…you can skip ahead until the loading indicator is about done.)

https://share.cleanshot.com/DtSFSltB

What's happening here is I submit a post right after the file upload indicator shows that the file has completed uploading, yet when I look at either our published or editor view of the post, the image is broken. I can confirm that the image upload to S3 did not complete. My suspicion is that the upload indicator looks like the upload is complete before the file _actually_ reaches the destination.

We've had a few customers hit this sort of thing where they were sure they let an image finish uploading, but then find it "lost" when they go to view or edit their posts.

Anyway, I just wanted to get something started here to see if it gives you any 💡s. I'm happy to do my best at providing more information as you need it.

(Separately, I would love something to hook into so I can interrupt form submission if any uploads are not yet complete.)

**Comment by KonnorRogers** [comment]
🤔 Odd. Definitely unexpected. The reproduction helps tremendously. That sounds accurate.
 And now I'm curious if I can reproduce with Trix 😆 

Hooks for interrupting form submissions for pending uploads seems totally doable.

No reason there can't be an array of "in-flight" attachments.

Something like:

```
rhinoEditor.pendingAttachments.length // => 1
````

Seems reasonable to me.

**Comment by KonnorRogers** [comment]
🤔 I'm almost curious if when the upload completes, we should make a follow up request for the image, and only show the upload as completing once we can properly get the image from wherever its hosted.

Let me do some research and poke around with this a little bit.

**Comment by bjhess** [comment]
That's a pretty interesting way to confirm a successful upload. Curious what you find!

**Comment by KonnorRogers** [comment]
So this may be a really silly idea, but I _think_ I have a solution for this. I'm not 100% what the cap should be, but right now locally I can reproduce the issue, I found requesting the object seems to be pretty "fool proof"

So the idea I may live to regret is capping "progress" at 90%, and then it can only ever get to 100% once the re-fetch completes.

This way, we guarantee it _actually_ uploaded.

**Comment by KonnorRogers** [comment]
https://github.com/user-attachments/assets/29635e9d-888c-4954-89e8-13a9b0ea3648

^ Here's a video of it locally.
