### ISSUE TITLE
How to show the character count info?

### ISSUE THREAD

**Issue by fractaledmind** [KonnorRogers/rhino-editor#23]
In the "Setup" section, you give the example of plugging in the [`CharacterCount`](https://tiptap.dev/api/extensions/character-count) TipTap extension. The React example in the TipTap docs shows the character count info on the page. In trying to use `rhino-editor`, I wanted to setup the extension and also show the info. I can't figure out how to do that, however, because I can't figure out how to get a reference to the `editor` object defined on the `RhinoEditor` web component. 

Any suggestions here?

**Comment by KonnorRogers** [comment]
@fractaledmind to get a reference to the TipTap editor you need to grab the element and then call `.editor` so in this case I'd do something like this:

`document.querySelector("rhino-editor").editor.storage.characterCount.characters()`

**Comment by KonnorRogers** [comment]
https://rhino-editor.vercel.app/tutorials/setup/#character-count-example

@fractaledmind
