### ISSUE TITLE
When cancelling an upload, it seems to still be working in the background?

### ISSUE THREAD

**Issue by bjhess** [KonnorRogers/rhino-editor#236]
I'm not sure if this is resolvable. And it's not a huge deal, IMO. But I wanted to register it because I saw it.

After tying into [the `pendingAttachments` capability of direct uploads](https://rhino-editor.vercel.app/editor-events/#waiting-to-submit-a-form-until-direct-uploads-finish), I noticed that if I cancel an upload the `pendingAttachments` array is still populated until [some point when it gets cleared].

Here's a video proving it (the alert happens when `pendingAttachments.length > 0`):

https://share.cleanshot.com/5RPZrJdf

**Comment by KonnorRogers** [comment]
Oh hang on. I believe I know the fix for this. There's an appendTransaction in Rhino that needs to clear this.

**Comment by KonnorRogers** [comment]
Fixed in 0.14.3! If its still giving you problems, feel free to re-open this or open a new issue.

**Comment by bjhess** [comment]
Just did a quick check and I think it's working. Thank you!
