### ISSUE TITLE
clicking on "compare to trix" does not work

### ISSUE THREAD

**Issue by yshmarov** [KonnorRogers/rhino-editor#63]
on the homepage, clicking on "compare to trix" does not work

![testing](https://user-images.githubusercontent.com/13472945/235316305-a459fcbc-673d-4268-bc8b-2e8296573354.gif)

**Comment by KonnorRogers** [comment]
@yshmarov i hate Vercel.

it's supposed to 404 because I haven't written it yet, but for some reason 404s don't actually work on Vercel because they expect everyone to use an SPA.

**Comment by KonnorRogers** [comment]
Related:
https://github.com/withastro/astro/issues/4164

I'll just put a placeholder there for now since this is like the 4th report

**Comment by KonnorRogers** [comment]
Fixed in #66
